### ISSUE TITLE
staticcheck: fix issues from old repository

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#13]
Work on the following issues: 

- [ ] dominikh/go-staticcheck#70 - Checks equivalent to Aspirator
- [x] dominikh/go-staticcheck#68 - Ticker not stopped
- [x] dominikh/go-staticcheck#67 - Detect invocations of os.Exit in func assigned to flag.Usage or flag.FlagSet.Usage.
- [ ] dominikh/go-staticcheck#65 - SA5006 triggers when ranging over slice of size 0
- [ ] dominikh/go-staticcheck#63 - detect math.Pow() with small positive constants
- [x] dominikh/go-staticcheck#61 - Don't report discarded pure function results in benchmarks
- [ ] dominikh/go-staticcheck#60 - SA2002 (T.Fatal called in non-main goroutine) can be fooled by depth
- [ ] dominikh/go-staticcheck#57 - vrp: support propagating ranges backwards
- [ ] dominikh/go-staticcheck#56 - VRP: support declaring function's return value as a function of one of its inputs
- [ ] dominikh/go-staticcheck#54 - Detect useless continue/break statements
- [ ] dominikh/go-staticcheck#53 - Avoid flagging the same mistake twice
- [ ] dominikh/go-staticcheck#46 - Detect branches with identical code
- [ ] dominikh/go-staticcheck#39 - Check sequential tests with identical conditions
- [ ] dominikh/go-staticcheck#37 - VRP: implement all arithmetic operators
- [ ] dominikh/go-staticcheck#36 - VRP: support slices started
- [ ] dominikh/go-staticcheck#35 - VRP: support pointers
- [ ] dominikh/go-staticcheck#34 - VRP: support strings started
- [ ] dominikh/go-staticcheck#33 - VRP: special cases for the standard library
- [ ] dominikh/go-staticcheck#32 - VRP: Get tighter ranges when integer overflow occurs
- [ ] dominikh/go-staticcheck#23 - Support more scenarios in SA1001
- [ ] dominikh/go-staticcheck#17 - Detect type inconsistencies
- [ ] dominikh/go-staticcheck#15 - Check for alignment of variables used in atomic access.

**Comment by dominikh** [comment]
Migrated all remaining issues to this repo's issue tracker.
