### ISSUE TITLE
Investigate subset of go-critic checks that are useful

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#305]
- [ ] [builtinShadow](https://go-critic.github.io/overview#builtinshadow) – non-default stylecheck
- [ ] [caseOrder](https://go-critic.github.io/overview#caseorder) – staticcheck
- [ ] [deadCodeAfterLogFatal](https://go-critic.github.io/overview#deadcodeafterlogfatal) – gosimple, dup of #111 
- [ ] [defaultCaseOrder](https://go-critic.github.io/overview#defaultcaseorder) – stylecheck
- [ ] [dupBranchBody](https://go-critic.github.io/overview#dupbranchbody) – staticcheck, dup of #174 
- [ ] [dupCase](https://go-critic.github.io/overview#dupcase) – gosimple
- [ ] [elseif](https://go-critic.github.io/overview#elseif) – stylecheck or gosimple
- [ ] [evalOrder](https://go-critic.github.io/overview#evalorder) – staticcheck, dup of #258 
- [ ] [flagDeref](https://go-critic.github.io/overview#flagderef) – staticcheck
- [ ] [importShadow](https://go-critic.github.io/overview#importshadow) – non-default stylecheck
- [ ] [indexOnlyLoop](https://go-critic.github.io/overview#indexonlyloop) – gosimple
- [ ] [initClause](https://go-critic.github.io/overview#initclause) – stylecheck or gosimple
- [ ] [regexpMust](https://go-critic.github.io/overview#regexpmust) – stylecheck
- [ ] [singleCaseSwitch](https://go-critic.github.io/overview#singlecaseswitch) – stylecheck or gosimple
- [ ] [sloppyLen](https://go-critic.github.io/overview#sloppylen) – staticcheck
- [ ] [typeSwitchVar](https://go-critic.github.io/overview#typeswitchvar) – gosimple, dup of #126 
- [ ] [yodaStyleExpr](https://go-critic.github.io/overview#yodastyleexpr) – non-default stylecheck

**Comment by Quasilyte** [comment]
I think `initClause` fits stylecheck more, because it's not really a simplification, but rather an effort of avoiding code with surprises.

**Comment by Quasilyte** [comment]
`singleCaseSwitch` can benefit from `TODO` comments checks.
Some switches with a single case have something like: "TODO: cover all things later".
These may be better left alone, at least by default.
This case is not handled by gocritic since it's not really convenient to match comments (non-doc comments) to arbitrary statement.

**Comment by Quasilyte** [comment]
`elseif` finds many cases where code can be less beautiful when re-written.
See https://github.com/go-critic/go-critic/issues/420.
I don't know whether my approach gives good enough reduce in these false-positive like cases.
There can be issues in determining 100%-fine replacements.
