### ISSUE TITLE
Ponder gosimple vs quickfix

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#474]
# Description

We should evaluate every check in gosimple to see if it's better suited for quickfix (in-editor code fixes). Ideally, we never added any checks to gosimple that shouldn't be in gosimple, but of course people make mistakes, and our understanding of tooling has changed in the past couple of years.

Checks that seem opinionated or don't universally improve readability should not be in gosimple. Gosimple should only flag code that is unquestionable less clear than it could be. Quickfix, on the other hand, can contain all of the "hey, how about writing your code this way instead" suggestions.

# Existing checks

We need to make a decision for each of these checks:

- [ ] [S1000](https://staticcheck.io/docs/checks#S1000) – Use plain channel send or receive instead of single-case select
- [ ] [S1001](https://staticcheck.io/docs/checks#S1001) – Use copy() instead of loop
- [ ] [S1002](https://staticcheck.io/docs/checks#S1002) – Omit comparison with boolean constant
- [ ] [S1003](https://staticcheck.io/docs/checks#S1003) – Use strings.Contains instead of strings.Index() != -1
- [ ] [S1004](https://staticcheck.io/docs/checks#S1004) – Use bytes.Equal instead of bytes.Compare() == 0
- [ ] [S1005](https://staticcheck.io/docs/checks#S1005) – Drop unnecessary use of the blank identifier
- [ ] [S1006](https://staticcheck.io/docs/checks#S1006) – Replace 'for true { ... }' with for { ... }
- [ ] [S1007](https://staticcheck.io/docs/checks#S1007) – Simplify regular expression by using raw string literal
- [ ] [S1008](https://staticcheck.io/docs/checks#S1008) – Simplify returning boolean expression
- [ ] [S1009](https://staticcheck.io/docs/checks#S1009) – Omit redundant nil check on slices
- [ ] [S1010](https://staticcheck.io/docs/checks#S1010) – Omit default slice index
- [ ] [S1011](https://staticcheck.io/docs/checks#S1011) – Use a single append to concatenate two slices
- [ ] [S1012](https://staticcheck.io/docs/checks#S1012) – Use time.Since(x) instead of time.Now().Sub(x)
- [ ] [S1016](https://staticcheck.io/docs/checks#S1016) – Use a type conversion instead of copying struct fields
- [ ] [S1017](https://staticcheck.io/docs/checks#S1017) – Replace with strings.TrimPrefix
- [ ] [S1018](https://staticcheck.io/docs/checks#S1018) – Use copy() for sliding elements in a slice
- [ ] [S1019](https://staticcheck.io/docs/checks#S1019) – Simplify make call
- [ ] [S1020](https://staticcheck.io/docs/checks#S1020) – Omit redundant nil check in type assertion
- [ ] [S1021](https://staticcheck.io/docs/checks#S1021) – Merge variable declaration and assignment
- [ ] [S1023](https://staticcheck.io/docs/checks#S1023) – Omit redundant control flow
- [ ] [S1024](https://staticcheck.io/docs/checks#S1024) – Use time.Until(x) instead of x.Sub(time.Now())
- [ ] [S1025](https://staticcheck.io/docs/checks#S1025) – Don't use fmt.Sprintf("%s", x) unnecessarily
- [ ] [S1028](https://staticcheck.io/docs/checks#S1028) – Use fmt.Errorf instead of errors.New(fmt.Sprintf(...))
- [ ] [S1029](https://staticcheck.io/docs/checks#S1029) – Range over the string instead of []rune(s)
- [ ] [S1030](https://staticcheck.io/docs/checks#S1030) – Use bytes.Buffer.String or bytes.Buffer.Bytes
- [ ] [S1031](https://staticcheck.io/docs/checks#S1031) – Omit redundant nil check around loop
- [ ] [S1032](https://staticcheck.io/docs/checks#S1032) – Replace with sort.Ints(x), sort.Float64s(x), sort.Strings(x)

# Planned checks

Check all of these issues to see if they'd be better placed under quickfix.

- [ ] #447 – simple: recommend math/bits.RotateLeft*
- [ ] #358 – Flag using %s:%d to construct network addresses
- [ ] #282 – simple: suggest replacing x[:] with x where x type is string or slice
- [ ] #274 – simple: add check for python style map sums
- [ ] #256 – simple: suggest # flag in format strings when user manually recreates its effect
- [ ] #253 – simple: flag unnecessary assignment to the blank identifier
- [ ] #181 – gosimple: detect math.Pow() with small positive constants
- [ ] #147 – simple: unnecessary sync.WaitGroup usage
- [ ] #128 – simple: flag unnecessary integer type conversions inside index and slice expressions
- [ ] #123 – simple: suggest simplifying closures that are no-op call wrappers
- [ ] #102 – simple: check sync.RWMutex used only as a sync.Mutex
- [ ] #98 – simple: Missed opportunity for S1021 when assignment is multi-valued
- [ ] #78 – simple: Warn when a function return signature contains unnecessary variables
- [ ] #75 – simple: detect mostly identical branches
- [ ] #65 – simple: suggest merging for with if-break
- [ ] #40 – gosimple: unnecessary anonymous func
- [ ] #254 – gosimple: un-paren some classes of type expressions
- [ ] #240 – gosimple: suggest changing "break someLabel" with "break" when possible
- [ ] #151 – simple: single line if err check if no values used out of if statement
- [ ] #146 – simple: simplify `!(x op y)`
- [ ] #100 – simple: fmt.{Printf,Fprintf,Sprintf} without arguments can be simplified
- [ ] #52 – simple: unnecessary use of anonymous fields in selectors
- [ ] #9 – gosimple: suggest grouping of global vars/consts
