### ISSUE TITLE
Release 2019.2

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-tools#504]
Checklist of things we need to do before releasing 2019.2:

- [x] Write release notes
- [x] Update documentation
  - [x] Update section on resource usage. 
    - There is no longer any benefit to running staticcheck on fewer packages at a time.
    - Memory use is directly related to parallelism, mention GOMAXPROCS
    - Mention caching
  - [x] Update list of command line flags
  - [x] Update (or rather add) install instructions. Mention modules, versions and GitHub release watches (#392, #406)
  - [x] Update example of JSON output format
  - [x] Regenerate checks documentation
- [ ] ~~Make sure our module proxy is in place and working (#498)~~
- [x] Add issue templates. We want those to be ready for when people inevitably report bugs (#496)
- [x] Update our build script 
  - [ ] ~Strip local paths (#470)~
  - [x] Build as a module so we get useful version information
- [x] Update website navigation to link to `https://github.com/dominikh/go-tools/?sponsor=1` instead of just Patreon.
- [x] Actually remove the `-ignore` flag
- [x] Update project README with new links and text matching the website

**Comment by dominikh** [comment]
The first draft of the release notes is done and at https://github.com/dominikh/go-tools/blob/master/doc/2019.2.html – happy for people to review the notes and provide feedback.

**Comment by ainar-g** [comment]
The lines 164–165 are not indented. I haven't noticed any other issues.

**Comment by tendervittles** [comment]
It is a missed opportunity to not have ST1017’s description be “Use Yoda conditions do not.”

**Comment by dominikh** [comment]
I appreciate the humor. Unfortunately we're obligated to being 100% serious all the time, lest someone gets confused and blows up an Ariane 5.
